/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasta;
import javax.swing.JOptionPane;
/**
 *
 * @author asus
 */
public class biodata extends javax.swing.JFrame {

    /**
     * Creates new form biodata
     */
    public biodata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cKursi = new javax.swing.JComboBox<>();
        nKursi = new javax.swing.JComboBox<>();
        studio = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        proses = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        film = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cKursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G" }));
        getContentPane().add(cKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 170, 50));

        nKursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(nKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 190, 50));

        studio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Studio 1", "Studio 2", "Studio 3", "Studio 4" }));
        getContentPane().add(studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 280, 40));

        nama.setBorder(null);
        nama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nama.setOpaque(false);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 430, 40));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("The Devil Net", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KEMBALI");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 130, 50));

        proses.setBackground(new java.awt.Color(51, 51, 51));
        proses.setFont(new java.awt.Font("The Devil Net", 0, 18)); // NOI18N
        proses.setForeground(new java.awt.Color(255, 255, 255));
        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, 130, 50));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("The Devil Net", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SEAT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 110, 60));

        film.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JOHN WICK CHAPTER 3 - PARABELLUM", "POKEMON DETECTIVE PIKACHU", "AVENGER - ENDGAME" }));
        getContentPane().add(film, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\oprec\\bio0000.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new tugasTA2().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    new seat().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        nama.setText(nama.getText());
        cKursi.getSelectedItem().toString();
        nKursi.getSelectedItem().toString();
        studio.getSelectedItem().toString();
        film.getSelectedItem().toString();
         {
             if(nama.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Kolom Nama harus diisi dulu gan");
             new biodata().setVisible(true);
             nama.setText("");
             
         }
             biodata tampiljop = new biodata();
    String pesan[]= {"Nama                : "+nama.getText(),
                     "Kode Kursi       : "+cKursi.getSelectedItem()+""+nKursi.getSelectedItem(),
                     "Studio                : "+studio.getSelectedItem(),
                     "Judul Film         : "+film.getSelectedItem(),
                     "",
                     "Harga tiketnya sebesar Rp40.000,-",
                     "=======================================",
                     "Klik tombol OK untuk mencetak tiket anda"};
    JOptionPane.showMessageDialog(tampiljop,pesan);                  
    }
         
      new penutup().setVisible(true);
     this.dispose();   
    }//GEN-LAST:event_prosesActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cKursi;
    private javax.swing.JComboBox<String> film;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> nKursi;
    private javax.swing.JTextField nama;
    private javax.swing.JButton proses;
    private javax.swing.JComboBox<String> studio;
    // End of variables declaration//GEN-END:variables
}
