/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasta;

/**
 *
 * @author asus
 */
public class tugasTA2 extends javax.swing.JFrame {

    /**
     * Creates new form tugasTA2
     */
    public tugasTA2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        next1 = new javax.swing.JButton();
        sAve = new javax.swing.JButton();
        sJohn = new javax.swing.JButton();
        sPika = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        next1.setBackground(new java.awt.Color(51, 51, 51));
        next1.setFont(new java.awt.Font("The Devil Net", 0, 18)); // NOI18N
        next1.setForeground(new java.awt.Color(255, 255, 255));
        next1.setText("NEXT");
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        getContentPane().add(next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 650, 130, 40));

        sAve.setBackground(new java.awt.Color(51, 51, 51));
        sAve.setFont(new java.awt.Font("The Devil Net", 0, 18)); // NOI18N
        sAve.setForeground(new java.awt.Color(255, 255, 255));
        sAve.setText("SINOPSIS");
        sAve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAveActionPerformed(evt);
            }
        });
        getContentPane().add(sAve, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 130, 40));

        sJohn.setBackground(new java.awt.Color(51, 51, 51));
        sJohn.setFont(new java.awt.Font("The Devil Net", 0, 18)); // NOI18N
        sJohn.setForeground(new java.awt.Color(255, 255, 255));
        sJohn.setText("SINOPSIS");
        sJohn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sJohnActionPerformed(evt);
            }
        });
        getContentPane().add(sJohn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 130, 40));

        sPika.setBackground(new java.awt.Color(51, 51, 51));
        sPika.setFont(new java.awt.Font("The Devil Net", 0, 18)); // NOI18N
        sPika.setForeground(new java.awt.Color(255, 255, 255));
        sPika.setText("SINOPSIS");
        sPika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPikaActionPerformed(evt);
            }
        });
        getContentPane().add(sPika, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\oprec\\PILIHAN0000.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        new biodata().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_next1ActionPerformed

    private void sJohnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sJohnActionPerformed
  new sjohnwick().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_sJohnActionPerformed

    private void sPikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPikaActionPerformed
     new spika().setVisible(true);
     this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_sPikaActionPerformed

    private void sAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAveActionPerformed
     new save().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_sAveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugasTA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugasTA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugasTA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugasTA2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugasTA2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next1;
    private javax.swing.JButton sAve;
    private javax.swing.JButton sJohn;
    private javax.swing.JButton sPika;
    // End of variables declaration//GEN-END:variables
}
